# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label1 = QtWidgets.QLabel(Form)
        self.label1.setObjectName("label1")
        self.verticalLayout.addWidget(self.label1)
        self.slider1 = QtWidgets.QSlider(Form)
        self.slider1.setOrientation(QtCore.Qt.Horizontal)
        self.slider1.setMinimum(0)
        self.slider1.setMaximum(180)
        self.slider1.setProperty("value", 0)
        self.slider1.setObjectName("slider1")
        self.verticalLayout.addWidget(self.slider1)
        self.label2 = QtWidgets.QLabel(Form)
        self.label2.setObjectName("label2")
        self.verticalLayout.addWidget(self.label2)
        self.slider2 = QtWidgets.QSlider(Form)
        self.slider2.setOrientation(QtCore.Qt.Horizontal)
        self.slider2.setMinimum(0)
        self.slider2.setMaximum(180)
        self.slider2.setProperty("value", 0)
        self.slider2.setObjectName("slider2")
        self.verticalLayout.addWidget(self.slider2)
        self.label3 = QtWidgets.QLabel(Form)
        self.label3.setObjectName("label3")
        self.verticalLayout.addWidget(self.label3)
        self.slider3 = QtWidgets.QSlider(Form)
        self.slider3.setOrientation(QtCore.Qt.Horizontal)
        self.slider3.setMinimum(0)
        self.slider3.setMaximum(180)
        self.slider3.setProperty("value", 0)
        self.slider3.setObjectName("slider3")
        self.verticalLayout.addWidget(self.slider3)
        self.label4 = QtWidgets.QLabel(Form)
        self.label4.setObjectName("label4")
        self.verticalLayout.addWidget(self.label4)
        self.slider4 = QtWidgets.QSlider(Form)
        self.slider4.setOrientation(QtCore.Qt.Horizontal)
        self.slider4.setMinimum(0)
        self.slider4.setMaximum(180)
        self.slider4.setProperty("value", 0)
        self.slider4.setObjectName("slider4")
        self.verticalLayout.addWidget(self.slider4)
        self.lblPos = QtWidgets.QLabel(Form)
        self.lblPos.setObjectName("lblPos")
        self.verticalLayout.addWidget(self.lblPos)
        self.btnPick = QtWidgets.QPushButton(Form)
        self.btnPick.setObjectName("btnPick")
        self.verticalLayout.addWidget(self.btnPick)
        self.btnPlace = QtWidgets.QPushButton(Form)
        self.btnPlace.setObjectName("btnPlace")
        self.verticalLayout.addWidget(self.btnPlace)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Control Robot 4R"))
        self.label1.setText(_translate("Form", "Articulación 1: 0°"))
        self.label2.setText(_translate("Form", "Articulación 2: 0°"))
        self.label3.setText(_translate("Form", "Articulación 3: 0°"))
        self.label4.setText(_translate("Form", "Articulación 4: 0°"))
        self.lblPos.setText(_translate("Form", "Posición final: (x, y, z)"))
        self.btnPick.setText(_translate("Form", "Pick"))
        self.btnPlace.setText(_translate("Form", "Place"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
