# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setStyleSheet("font-size:16pt; font-weight:bold; color:black;")
        self.label_title.setObjectName("label_title")
        self.verticalLayout.addWidget(self.label_title)
        self.group_servos = QtWidgets.QGroupBox(self.centralwidget)
        self.group_servos.setObjectName("group_servos")
        self.formLayout = QtWidgets.QFormLayout(self.group_servos)
        self.formLayout.setObjectName("formLayout")
        self.label_base = QtWidgets.QLabel(self.group_servos)
        self.label_base.setObjectName("label_base")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_base)
        self.slider_base = QtWidgets.QSlider(self.group_servos)
        self.slider_base.setOrientation(QtCore.Qt.Horizontal)
        self.slider_base.setMinimum(0)
        self.slider_base.setMaximum(180)
        self.slider_base.setObjectName("slider_base")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.slider_base)
        self.label_hombro = QtWidgets.QLabel(self.group_servos)
        self.label_hombro.setObjectName("label_hombro")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_hombro)
        self.slider_hombro = QtWidgets.QSlider(self.group_servos)
        self.slider_hombro.setOrientation(QtCore.Qt.Horizontal)
        self.slider_hombro.setMinimum(0)
        self.slider_hombro.setMaximum(180)
        self.slider_hombro.setObjectName("slider_hombro")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.slider_hombro)
        self.label_codo = QtWidgets.QLabel(self.group_servos)
        self.label_codo.setObjectName("label_codo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_codo)
        self.slider_codo = QtWidgets.QSlider(self.group_servos)
        self.slider_codo.setOrientation(QtCore.Qt.Horizontal)
        self.slider_codo.setMinimum(0)
        self.slider_codo.setMaximum(180)
        self.slider_codo.setObjectName("slider_codo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.slider_codo)
        self.label_muneca = QtWidgets.QLabel(self.group_servos)
        self.label_muneca.setObjectName("label_muneca")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_muneca)
        self.slider_muneca = QtWidgets.QSlider(self.group_servos)
        self.slider_muneca.setOrientation(QtCore.Qt.Horizontal)
        self.slider_muneca.setMinimum(0)
        self.slider_muneca.setMaximum(180)
        self.slider_muneca.setObjectName("slider_muneca")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.slider_muneca)
        self.label_pinza = QtWidgets.QLabel(self.group_servos)
        self.label_pinza.setObjectName("label_pinza")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_pinza)
        self.slider_pinza = QtWidgets.QSlider(self.group_servos)
        self.slider_pinza.setOrientation(QtCore.Qt.Horizontal)
        self.slider_pinza.setMinimum(0)
        self.slider_pinza.setMaximum(180)
        self.slider_pinza.setObjectName("slider_pinza")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.slider_pinza)
        self.verticalLayout.addWidget(self.group_servos)
        self.group_actuador = QtWidgets.QGroupBox(self.centralwidget)
        self.group_actuador.setObjectName("group_actuador")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.group_actuador)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_pick = QtWidgets.QPushButton(self.group_actuador)
        self.btn_pick.setStyleSheet("background-color:#d4edda; font-weight:bold;")
        self.btn_pick.setObjectName("btn_pick")
        self.horizontalLayout.addWidget(self.btn_pick)
        self.btn_place = QtWidgets.QPushButton(self.group_actuador)
        self.btn_place.setStyleSheet("background-color:#cce5ff; font-weight:bold;")
        self.btn_place.setObjectName("btn_place")
        self.horizontalLayout.addWidget(self.btn_place)
        self.verticalLayout.addWidget(self.group_actuador)
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Control Manual - Brazo Robótico (Raspberry Pi 4)"))
        self.label_title.setText(_translate("MainWindow", "🦾 Control Manual del Brazo Robótico"))
        self.group_servos.setTitle(_translate("MainWindow", "Control de Servos"))
        self.label_base.setText(_translate("MainWindow", "Base (rotación)"))
        self.label_hombro.setText(_translate("MainWindow", "Hombro (sincronizado)"))
        self.label_codo.setText(_translate("MainWindow", "Codo"))
        self.label_muneca.setText(_translate("MainWindow", "Muñeca"))
        self.label_pinza.setText(_translate("MainWindow", "Pinza (manual)"))
        self.group_actuador.setTitle(_translate("MainWindow", "Actuador Final (Pinza)"))
        self.btn_pick.setText(_translate("MainWindow", "Pick (Cerrar)"))
        self.btn_place.setText(_translate("MainWindow", "Place (Abrir)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
